component_depth: 2
languages:
  - name: cpp
    production:
      include:
        - /include.*\.hpp
        - /include/test.*\.hpp
      exclude:
        - /test.*\.[hc]pp
    test:
      include:
        - /test.*\.[hc]pp
      exclude:
        - /include.*\.hpp