os:
    - linux
    - osx

sudo: required

services:
    - docker

language: minimal

addons:
  apt:
    packages:
      - python-pip

compiler:
    - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull debian:sid-slim; fi
    - mkdir reports
    - export BUILD_DIR=$TRAVIS_BUILD_DIR

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install --upgrade pip; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install spline; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then spline; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd test; clang++ -o test_seq -std=c++11 main.cpp basic_tests.cpp reflexive_tests.cpp; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then clang++ -o test_par -fopenmp -std=c++11 main.cpp basic_tests.cpp reflexive_tests.cpp; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./test_seq; ./test_par; cd ..; fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
        on_failure: change
