sudo: required

services:
    - docker

language: minimal

addons:
  apt:
    packages:
      - python-pip

before_install:
    - docker pull debian:sid-slim
    - mkdir reports

install:
    - gem install coveralls-lcov
    - sudo pip install --upgrade pip
    - sudo pip install spline

script:
    - spline

after_success:
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} reports/cov.info

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
on_failure: change
