os:
    - linux

dist: trusty
sudo: required

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python-pip
      - g++-8

compiler:
    - gcc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-8; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp; fi
    - mkdir reports

install:
    - sudo pip install --upgrade pip
    - sudo pip install spline

script:
    - spline --tags=$TRAVIS_OS_NAME

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
        on_failure: change
