sudo: required

services:
    - docker

language: minimal

addons:
  apt:
    packages:
      - python-pip

before_install:
    - docker pull debian:sid-slim
    - mkdir reports
    - export BUILD_DIR=$TRAVIS_BUILD_DIR

install:
    - sudo pip install --upgrade pip
    - sudo pip install spline

script:
    - spline

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
        on_failure: change
