os:
    - linux
    - osx

sudo: required

services:
    - docker

language: minimal

addons:
  apt:
    packages:
      - python-pip

compiler:
    - clang

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull debian:sid-slim; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp; fi
    - mkdir reports
    - export BUILD_DIR=$TRAVIS_BUILD_DIR

install:
    - sudo pip install --upgrade pip
    - sudo pip install spline

script:
    - spline --tags=$TRAVIS_OS_NAME

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
    email:
        recipients:
           - jarthianur.github@gmail.com
        on_success: change
        on_failure: change
