matrix:
  - name: C++11
    env: 
      cpp_std: c++11
    tags: 
    - c++11
  - name: C++14
    env: 
      cpp_std: c++14
    tags: 
    - c++14
  - name: C++17
    env: 
      cpp_std: c++17
    tags: 
    - c++17

model:
  variables:
    build_dir: build_{{ env.cpp_std }}
  templates:
    linux:
      build_script: |
        mkdir $BUILD_DIR
        mkdir -p reports/{{ env.cpp_std }}
        cp -r test src sctf.hpp $BUILD_DIR/
        pushd $BUILD_DIR
        cp -r test test_p
        pushd test/
        $CXX -o test_seq -g3 -O0 -fprofile-arcs -ftest-coverage -coverage -std={{ env.cpp_std }} main.cpp basic_tests.cpp reflexive_tests.cpp
        popd
        pushd test_p/
        $CXX -o test_par -fopenmp -g3 -O0 -fprofile-arcs -ftest-coverage -coverage -std={{ env.cpp_std }} main.cpp basic_tests.cpp reflexive_tests.cpp
        popd
        popd
      test_script: |
        pushd $BUILD_DIR
        pushd test/
        $LCOV -c -i -d . -o base.info
        ./test_seq
        $LCOV -c -d . -o test.info
        $LCOV -a base.info -a test.info -o seq.info
        popd
        pushd test_p/
        $LCOV -c -i -d . -o base.info
        ./test_par
        $LCOV -c -d . -o test.info
        $LCOV -a base.info -a test.info -o par.info
        popd
        $LCOV -a test/seq.info -a test_p/par.info -o all.info
        $LCOV -e all.info "$PWD/src/*" -o ../reports/{{ env.cpp_std }}/lcov.info
        popd
    osx:
      build_script: |
        pushd test
        clang++ -o test_seq -std={{ env.cpp_std }} main.cpp basic_tests.cpp reflexive_tests.cpp
        clang++ -o test_par -Xpreprocessor -fopenmp -std={{ env.cpp_std }} -lomp main.cpp basic_tests.cpp reflexive_tests.cpp
        popd
      test_script: |
        test/test_seq
        test/test_par

pipeline:
- stage(analysis):
  - tasks(ordered):
    - shell:
        script: |
          for f in $(find src/ -type f); do
            diff -u <(cat $f) <($CFMT -style=file $f) || true
          done &> /tmp/format.diff
          if [ "$(wc -l /tmp/format.diff | cut -d' ' -f1)" -gt 0 ]; then
            cat /tmp/format.diff
            exit 1
          fi
        tags:
        - linux

- stage(build):
  - tasks(ordered):
    - shell:
        script: |
          BUILD_DIR={{ model.variables.build_dir|render(env=env) }}
          {{ model.templates.linux.build_script|render(env=env) }}
        tags:
        - linux

    - shell:
        script: |
          {{ model.templates.osx.build_script|render(env=env) }}
        tags:
        - osx

- stage(test):
  - tasks(ordered):
    - shell:
        script: |
          BUILD_DIR={{ model.variables.build_dir|render(env=env) }}
          {{ model.templates.linux.test_script|render(env=env) }}
        tags:
        - linux

    - shell:
        script: |
          {{ model.templates.osx.test_script|render(env=env) }}
        tags:
        - osx
