matrix(parallel):
  - name: C++11
    env: 
      CPP_STD: c++11
    tags: 
      - c++11
  - name: C++14
    env: 
      CPP_STD: c++14
    tags: 
      - c++14
  - name: C++17
    env: 
      CPP_STD: c++17
    tags: 
      - c++17

pipeline:
  - stage(Testing):
    - tasks(ordered):
      - docker(container):
          image: debian:sid-slim
          mount: true
          script: |
            case $1 in
              INIT)
                export LC_ALL=C
                apt-get update
                apt-get -y install git g++ g++-multilib tar wget make perl
                mkdir /build
                pushd /mnt/host/
                tar cvzf /build/testing.tar.gz $(git ls-files)
                popd
                pushd /build
                tar xzf testing.tar.gz
                rm -rf testing.tar.gz
                cp -r test test_p
                popd
                $0 RUN
              ;;
              RUN)
                pushd /build
                echo "BUILD SEQUENTIAL TEST BINARIES"
                pushd test
                g++ -o test_seq -g3 -O0 -std={{ env.CPP_STD }} main.cpp basic_tests.cpp reflexive_tests.cpp
                echo "RUN SEQUENTIAL TESTS"
                ./test_seq
                popd
                pushd test_p/
                echo "BUILD PARALLEL TEST BINARIES"
                g++ -o test_par -fopenmp -g3 -O0 -std={{ env.CPP_STD }} main.cpp basic_tests.cpp reflexive_tests.cpp
                echo "RUN PARALLEL TESTS"
                ./test_par
                popd
                popd
              ;;
            esac
